# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ReactComponentKitApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactComponentKitApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'BKRedux'
  pod 'BKEventBus'
  pod 'SnapKit'
  
  target 'ReactComponentKitAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
