# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'ReactComponentKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactComponentKit
  pod 'BKEventBus'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SnapKit', '~> 3.2.0'
end
